import { createContext, useContext, useState, ReactNode } from 'react';
import { Language, Dictionary } from '../types';

export const DICTIONARY: Record<Language, any> = {
  EN: {
    dashboard: "Analytics Suite",
    crmLeadTracker: "Luxury CRM Suite",
    aiLeadsFinder: "HNW Lead Hunter",
    auditLogs: "Secure Audit Ledger",
    teamAccess: "Admin & Team Matrix",
    language: "Language Selection",
    budget: "Investment Budget",
    status: "Pipeline Status",
    assignedAgent: "Assigned Executive",
    lastContact: "Last Interaction",
    nextFollowUp: "Autopilot Action Slate",
    actionLogs: "Access Logs",
    realtimeSync: "Cloud Sync Enabled",
    encryptedText: "End-to-End Encrypted",
    role: "Operational Role",
    addLead: "Onboard New Prospect",
    propertyMatching: "Luxury Portfolio Matcher",
    performanceAnalytics: "AI Intelligence Suite",
    autoPilotFollowUps: "Autopilot Follow-Up Writer",
    appBrand: "MALLORCA AGENTS",
    appSubtitle: "Elite CRM & Autonomous AI Lead Intelligence Suite",
    totalInterest: "Total Liquid Interest on Mallorca",
    avgBudget: "Avg Target Budget / SQM",
    runningBots: "Autonomous AI Bots Running",
    convRate: "Lead Conversion Rate",
    prospectLedger: "PROSPECT LEDGER",
    searchPlaceholder: "Search investors database...",
    selectAll: "All Statuses",
    minBudget: "Minimum Budget",
    maxBudget: "Maximum Budget",
    allSources: "All Sources",
    allAgents: "All Agents",
    filterAgent: "Filter by Agent",
    newest: "Newest First",
    budgetHighLow: "Budget (High-Low)",
    alphabetical: "Alphabetical",
    engagementScore: "Social Engagement & Activity",
    dossierHeader: "INVESTOR DOSSIER FILE",
    noLeadSelected: "No prospect folder selected. Choose a lead form in the ledger for deep auditing.",
    phone: "Phone",
    source: "Source",
    socialHandle: "Social Channel Account",
    notes: "Notes & Context",
    interestedProp: "Interested Luxury Property",
    copyDossier: "Copy Dossier to Clipboard",
    generateFollowUp: "Generate Autopilot Follow-Up",
    deleteFolder: "Delete Prospect Folder",
    timelineHeader: "TIMELINE ACTIVITY LEDGER",
    targetChannel: "Target Channel Setup",
    targetNiche: "Target Luxury Niche",
    initiateScrape: "Initiate Live AI Lead Capture",
    autopilotOn: "Autopilot Active (Interval: 30s)",
    autopilotOff: "Activate Autopilot Auto-Mining",
    telemetry: "Hunter System Telemetry",
    generateInsight: "Generate Live Performance Analytics",
    permissionsMatrix: "SECURE OPERATIONS PERMISSIONS MATRIX",
    demoHighlight: "DEMO HIGHLIGHT",
    allowed: "Allowed",
    restricted: "Restricted",
    impersonate: "Impersonate",
    roleAdmin: "Administrator",
    roleSales: "Sales Agent",
    roleSpecialist: "Lead Gen Specialist",
    addLeadBtn: "Onboard New Prospect",
    modalTitle: "REGISTER NEW REAL ESTATE PROSPECT",
    modalName: "Full Professional Name",
    modalEmail: "Verified E-mail Address",
    modalPhone: "Telephone / Contact Details",
    modalBudget: "Max Investment Budget",
    modalLang: "Primary Language Preference",
    modalSource: "Acquisition Target Source",
    modalNotes: "Contextual Background & Demands",
    modalCancel: "Cancel",
    modalSubmit: "Onboard Prospect Folder",
    encryptedDossier: "Encrypted Dossier Portfolio",
    noCustomNotes: "No custom agent notes entered.",
    socialTrack: "Social Track",
    investmentLimit: "Investment Limit",
    assignedExecutive: "Assigned Executive",
    purgeUser: "Purge",
    leadGenTrendTitle: "Social Lead Gen Performance Trends",
    liveFeed: "LIVE FEED",
    trendHint: "Configure & Scan Real-Time Social Feeds →",
    tourTitle: "Mallorca Agents Executive Training Course",
    tourSubtitle: "Interactive Application Walkthrough",
    statusTitle: "Systems Status",
    statusCurrentTab: "Current Tab:",
    statusRoster: "Mallorca Agents Roster:",
    statusProgress: "Training Progress:",
    stepPercent: "Complete",
    previous: "Previous",
    nextStep: "Next Step",
    loopTour: "Loop Tour",
    agentProTip: "Agent Pro-Tip:",
    tourInfoHint: "Click points or loops to learn and run actions step-by-step",
    tourHintIcon: "Luxury Agent Academy",
    tourHowDoesItWork: "How does the {title} work?",
    tourStepText: "Step {current} of {total}",
    tourStep1Title: "Executive Overview Dashboard",
    tourStep1Desc: "A centralized flight control deck. See high-net-worth buyer quotients, live synchronization counters across Mallorca Agents devices, and dynamic performance trends.",
    tourStep1Tip: "Tap on the golden trends chart directly to jump into action!",
    tourStep2Title: "CRM Prospect Tracking Vault",
    tourStep2Desc: "Manage dossiers of high-profile buyers looking for luxury villas in Son Vida or Port d'Andratx. Filter instantly by custom investment budgets and view timelines of communications.",
    tourStep2Tip: "Log client interactions or trigger the Gemini brain to draft personalized premium follow-up messages in English, German, or Spanish with a single click.",
    tourStep3Title: "Autonomous HNW Lead Hunter",
    tourStep3Desc: "Define custom buyer demographics (such as 'German Yacht Owners' or 'Tech Founders') and switch on the Autopilot. The background crawler scouts corporate news, public liquidations, and luxury registers 24/7 to push qualified buyer leads matching your listings directly into your CRM.",
    tourStep3Tip: "Turn on the Autopilot switch to witness active background searches and overnight lead delivery!",
    tourStep4Title: "Performance Diagnostic Engine",
    tourStep4Desc: "Generate deep qualitative diagnosis reports using Gemini. Analyze acquisition metrics and synthesize real-time off-market trends.",
    tourStep4Tip: "Click 'Generate AI Performance Analytics' to boot up AI synthesis.",
    tourStep5Title: "Team Matrix & Security Desk",
    tourStep5Desc: "Moritz and Sebastian's private coordinator room. Add fresh sales agents, manage access credentials, or expand the secure Activity Ledger for deep operational audits.",
    tourStep5Tip: "Create team members securely, and impersonate Elena Ramos to experience sales-tier view limitations."
  },
  DE: {
    dashboard: "Analyse-Suite",
    crmLeadTracker: "Luxus-CRM-Verwaltung",
    aiLeadsFinder: "HNW Lead Jäger",
    auditLogs: "Sicherheits-Audit-Log",
    teamAccess: "Admin-Bereich & Team-Akte",
    language: "Sprachauswahl",
    budget: "Investitionsbudget",
    status: "Pipeline-Status",
    assignedAgent: "Zuständiger Berater",
    lastContact: "Letzter Kontakt",
    nextFollowUp: "Autopilot Wiedervorlage",
    actionLogs: "Zugriffsprotokolle",
    realtimeSync: "Cloud-Synchronisation Aktiv",
    encryptedText: "Ende-zu-Ende verschlüsselt",
    role: "Betriebliche Rolle",
    addLead: "Neuen Kunden anlegen",
    propertyMatching: "Immobilien-Matching",
    performanceAnalytics: "KI-Analyseberichte",
    autoPilotFollowUps: "Autopilot-Nachfassbriefe",
    appBrand: "MALLORCA AGENTS",
    appSubtitle: "Elite CRM & Autonome KI-Lead-Intelligenz-Suite",
    totalInterest: "Gesamtvolumen Liquidität (Mallorca)",
    avgBudget: "Durchschnittliches Budget / m²",
    runningBots: "Aktivierte KI-Scouting-Bots",
    convRate: "Pipeline-Erfolgsquote",
    prospectLedger: "KUNDEN-DATENBLATT",
    searchPlaceholder: "Investoren-Datenbank durchsuchen...",
    selectAll: "Alle Stati",
    minBudget: "Mindestbudget",
    maxBudget: "Maximalbudget",
    allSources: "Alle Quellen",
    allAgents: "Alle Berater",
    filterAgent: "Berater Filter",
    newest: "Neueste zuerst",
    budgetHighLow: "Budget (Hoch-Niedrig)",
    alphabetical: "Alphabetisch",
    engagementScore: "Social Engagement & Aktivität",
    dossierHeader: "INVESTOREN-DOSSIER",
    noLeadSelected: "Keine Kundenakte ausgewählt. Bitte wählen Sie einen Eintrag im Register zur detaillierten Einsicht.",
    phone: "Telefon",
    source: "Herkunft",
    socialHandle: "Social-Media-Kanal",
    notes: "Hintergrund & Details",
    interestedProp: "Interessantes Luxus-Objekt",
    copyDossier: "Dossier in Zwischenablage kopieren",
    generateFollowUp: "Autopilot-Follow-Up erstellen",
    deleteFolder: "Kundenakte vollständig löschen",
    timelineHeader: "TIMELINE-AKTIVITÄTSPROTOKOLL",
    targetChannel: "Zielkanaleinstellungen",
    targetNiche: "Angestrebte Käufer-Nische",
    initiateScrape: "Live-KI-Lead-Analysator starten",
    autopilotOn: "Autopilot Aktiv (Intervall: 30s)",
    autopilotOff: "Autopilot-Automatismus einschalten",
    telemetry: "Käufer-Sucher-Telemetrie",
    generateInsight: "Echtzeit-Performance-Bericht generieren",
    permissionsMatrix: "ROLLENBASIERTE SICHERHEITSMATRIX",
    demoHighlight: "DEMO-HINWEIS",
    allowed: "Zulässig",
    restricted: "Eingeschränkt",
    impersonate: "Rolle simulieren",
    roleAdmin: "Verwalter",
    roleSales: "Immobilienberater",
    roleSpecialist: "Marketing-Spezialist",
    addLeadBtn: "Neuen Kunden onboarden",
    modalTitle: "NEUEN KAUFINTERESSENTEN REGISTRIEREN",
    modalName: "Vollständiger Name des Kunden",
    modalEmail: "Verifizierte E-Mail-Adresse",
    modalPhone: "Telefonnummer / Kontakt",
    modalBudget: "Maximales Investitionsbudget",
    modalLang: "Präferierte Kommunikationssprache",
    modalSource: "Akquisitionsquelle des Leads",
    modalNotes: "Suchprofil & Spezifische Wünsche",
    modalCancel: "Abbrechen",
    modalSubmit: "Kundenakte anlegen & synchronisieren",
    encryptedDossier: "Verschlüsseltes Dossier-Portfolio",
    noCustomNotes: "Keine detaillierten Beraternotizen hinterlegt.",
    socialTrack: "Social-Media-Kanal",
    investmentLimit: "Investitionslimit",
    assignedExecutive: "Zuständiger Berater",
    purgeUser: "Sicher löschen",
    leadGenTrendTitle: "Social-Lead-Gen Performance-Trends",
    liveFeed: "LIVE-FEED",
    trendHint: "Echtzeit-Social-Feeds konfigurieren & scannen →",
    tourTitle: "Mallorca Agents Premium Lernakademie",
    tourSubtitle: "Interaktive CRM-Schulung & Einführung",
    statusTitle: "Systemstatus",
    statusCurrentTab: "Aktiver Tab:",
    statusRoster: "Mallorca Agents Team:",
    statusProgress: "Lernfortschritt:",
    stepPercent: "Abgeschlossen",
    previous: "Zurück",
    nextStep: "Nächster Schritt",
    loopTour: "Rundgang wiederholen",
    agentProTip: "Insider-Tipp:",
    tourInfoHint: "Klicken Sie auf Statuspunkte oder Schleifen, um das System kennenzulernen",
    tourHintIcon: "Berater-Akademie",
    tourHowDoesItWork: "Wie funktioniert {title}?",
    tourStepText: "Schritt {current} von {total}",
    tourStep1Title: "Chef-Übersichts-Dashboard",
    tourStep1Desc: "Ein zentrales Kontrolldeck. Sehen Sie hier Käufer-Quotienten für vermögende Investoren, Live-Synchronisierungsstatistiken aller Mallorca-Schnittstellen und dynamische Performance-Trends.",
    tourStep1Tip: "Klicken Sie direkt auf das goldene Balkendiagramm, um sofort aktiv zu werden!",
    tourStep2Title: "Kundenakte & CRM-Verwaltung",
    tourStep2Desc: "Verwalten Sie Dossiers von High-Profile-Käufern, die nach Luxusvillen in Son Vida oder Port d'Andratx suchen. Filtern Sie sekundenbereits nach Investitionsvolumen und sehen Sie Kontaktverläufe.",
    tourStep2Tip: "Protokollieren Sie Interaktionen oder lassen Sie die Gemini-KI personalisierte Premium-Nachrichten in Deutsch, Englisch oder Spanisch mit nur einem Klick verfassen.",
    tourStep3Title: "Autonomer HNW-Lead-Jäger",
    tourStep3Desc: "Definieren Sie exklusive Käuferprofile (wie 'Deutsche Yachtbesitzer' oder 'Technologie-Gründer') und schalten Sie den Autopiloten ein. Der Hintergrund-Crawler sucht rund um die Uhr in Verzeichnissen, Bilanzen und Luxusregistern, um qualifizierte Leads direkt in Ihre CRM-Suite zu übertragen.",
    tourStep3Tip: "Aktivieren Sie den 'Autopilot'-Schalter, um aktive Hintergrundrecherchen und kontinuierliche Lead-Lieferungen zu aktivieren!",
    tourStep4Title: "Leistungsanalyse-Engine",
    tourStep4Desc: "Generieren Sie qualitative tiefgehende Analysen mithilfe von Gemini. Bewerten Sie Konversionsraten und verfolgen Sie aktuelle Markttrends auf Mallorca.",
    tourStep4Tip: "Klicken Sie auf 'KI-Analysebericht generieren' um die KI-Synthese einzuleiten.",
    tourStep5Title: "Team-Matrix & Sicherheitszentrale",
    tourStep5Desc: "Moritz' & Sebastians privates Kontrollzentrum. Verwalten Sie Agentenprofile und Zugriffsrechte oder klappen Sie das detaillierte Aktivitätsprotokoll für administrative Prüfungen aus.",
    tourStep5Tip: "Erstellen Sie Agentenprofile sicher und wechseln Sie z. B. zu Elena Ramos, um Zugriffseinschränkungen live zu erleben."
  },
  ES: {
    dashboard: "Panel de Inteligencia",
    crmLeadTracker: "Gestión de CRM Premium",
    aiLeadsFinder: "Buscador de Leads HNW",
    auditLogs: "Historial de Auditoría",
    teamAccess: "Panel de Administración & Team",
    language: "Selección de Idioma",
    budget: "Presupuesto Inversión",
    status: "Fase de Negocio",
    assignedAgent: "Asesor Asignado",
    lastContact: "Último Contacto",
    nextFollowUp: "Plazos Autopilot",
    actionLogs: "Registros del Sistema",
    realtimeSync: "Sincronización en la Nube",
    encryptedText: "Cifrado de Extremo a Extremo",
    role: "Rol Operativo",
    addLead: "Registrar Nuevo Cliente",
    propertyMatching: "Casación de Villas",
    performanceAnalytics: "Informes Analíticos de IA",
    autoPilotFollowUps: "Generador de Seguimientos IA",
    appBrand: "MALLORCA AGENTS",
    appSubtitle: "CRM de Élite y Suite del Captador Inteligente IA",
    totalInterest: "Volumen Total de Interés Líquido",
    avgBudget: "Presupuesto Promedio / m²",
    runningBots: "Robots IA en Ejecución",
    convRate: "Tasa de Conversión de Clientes",
    prospectLedger: "REGISTRO DE PROSPECTOS",
    searchPlaceholder: "Buscar en base de inversores...",
    selectAll: "Todos los Estados",
    minBudget: "Presupuesto Mínimo",
    maxBudget: "Presupuesto Máximo",
    allSources: "Todas las Fuentes",
    allAgents: "Todos los Agentes",
    filterAgent: "Filtrar por Agente",
    newest: "Más nuevos primero",
    budgetHighLow: "Presupuesto (Mayor-Menor)",
    alphabetical: "Alfabético",
    engagementScore: "Interacción Social y Actividad",
    dossierHeader: "DOSSIER PRIVADO DEL INVERSOR",
    noLeadSelected: "Ningún prospecto seleccionado. Seleccione un expediente en el registro para inspeccionar.",
    phone: "Teléfono",
    source: "Origen",
    socialHandle: "Cuenta de Canal Social",
    notes: "Notas y Contexto",
    interestedProp: "Mansión de Interés Luxury",
    copyDossier: "Copiar Dossier al Portapapeles",
    generateFollowUp: "Generar Seguimiento Autopilot",
    deleteFolder: "Eliminar Expediente del Prospecto",
    timelineHeader: "HISTORIAL DE ACCIONES Y EVENTOS",
    targetChannel: "Configuración de Canal de Captación",
    targetNiche: "Nicho de Lujo Objetivo",
    initiateScrape: "Iniciar Captación de Clientes en Vivo",
    autopilotOn: "Autopilot Activo (Intervalo: 30s)",
    autopilotOff: "Activar Autominado Autopiloto",
    telemetry: "Telemetría del Captador Inteligente",
    generateInsight: "Generar Informe Crítico de Negocio",
    permissionsMatrix: "MATRIZ DE ACCESO DE SEGURIDAD EXCLUSIVA",
    demoHighlight: "NOTA DE DEMOSTRACIÓN",
    allowed: "Autorizado",
    restricted: "Restringido",
    impersonate: "Simular Rol",
    roleAdmin: "Administrador",
    roleSales: "Agente Ejecutivo",
    roleSpecialist: "Especialista en Captación",
    addLeadBtn: "Admitir Nuevo Prospecto",
    modalTitle: "REGISTRAR NUEVO PROSPECTO DE ALTA GAMA",
    modalName: "Nombre Profesional Completo",
    modalEmail: "Dirección de Correo Electrónico",
    modalPhone: "Teléfono / Datos de Contacto",
    modalBudget: "Presupuesto de Inversión Máximo",
    modalLang: "Preferencia de Idioma Primaria",
    modalSource: "Canal de Origen del Cliente",
    modalNotes: "Perfil de Búsqueda y Demandas",
    modalCancel: "Cancelar",
    modalSubmit: "Registrar Carpeta del Prospecto",
    encryptedDossier: "Dossier cifrado y protegido",
    noCustomNotes: "Sin notas de agente de ventas personalizadas.",
    socialTrack: "Canal de Seguimiento",
    investmentLimit: "Límite de Inversión",
    assignedExecutive: "Asesor Ejecutivo",
    purgeUser: "Purgar",
    leadGenTrendTitle: "Tendencias de Captación Social",
    liveFeed: "FEED EN VIVÓ",
    trendHint: "Configurar y Escanear Feeds Sociales en Vivo →",
    tourTitle: "Academia de Mallorca Agents",
    tourSubtitle: "Guía Interactiva de Entrenamiento Ejecutiva",
    statusTitle: "Estado de los Sistemas",
    statusCurrentTab: "Pestaña Activa:",
    statusRoster: "Plantilla de Ventas:",
    statusProgress: "Progreso de Formación:",
    stepPercent: "Completado",
    previous: "Anterior",
    nextStep: "Siguiente Paso",
    loopTour: "Reiniciar Tour",
    agentProTip: "Consejo de Élite:",
    tourInfoHint: "Haga clic en los puntos inferiores para aprender secuencialmente",
    tourHintIcon: "Academia de Agentes",
    tourHowDoesItWork: "¿Cómo funciona el {title}?",
    tourStepText: "Paso {current} de {total}",
    tourStep1Title: "Panel de Control Ejecutivo",
    tourStep1Desc: "Un centro de control unificado. Obtenga información sobre el volumen de interés líquido, sincronizaciones en la nube y tendencias de captación social interactiva.",
    tourStep1Tip: "¡Haga clic directamente en el gráfico dorado de barras para saltar a la acción!",
    tourStep2Title: "CRM de Expedientes y Ventas",
    tourStep2Desc: "Supervise las carpetas de compradores de alto standing que buscan villas de lujo en Son Vida o Port d'Andratx. Filtre por su presupuesto inversor o audite actividades históricas.",
    tourStep2Tip: "Registre interacciones de clientes o use la inteligencia de Gemini para redactar correos de seguimiento premium en español, inglés o alemán con un solo clic.",
    tourStep3Title: "Buscador Autónomo de Leads HNW",
    tourStep3Desc: "Defina perfiles de compradores exclusivos (como 'Propietarios de esloras premium' o 'Fundadores tech') y active el Autopilot. El crawler autónomo buscará 24/7 en registros corporativos, liquidaciones y clubes náuticos para ingresar prospectos con alto poder adquisitivo directamente en su CRM.",
    tourStep3Tip: "¡Active el interruptor de Autopilot para ver búsquedas de fondo activas y captación de clientes nocturna!",
    tourStep4Title: "Motor de Diagnóstico y Análisis",
    tourStep4Desc: "Genere informes cualitativos avanzados en segundos utilizando Gemini. Analice cuotas de conversión o examine tendencias fuera del mercado inmobiliario tradicional de Mallorca.",
    tourStep4Tip: "Inicie la síntesis de datos haciendo clic en 'Generar Informes Analíticos de IA'.",
    tourStep5Title: "Matriz del Equipo y Panel de Seguridad",
    tourStep5Desc: "La sala de control privada de Moritz y Sebastian. Administre perfiles de asesores, asigne credenciales de acceso o despliegue el historial completo de auditoría para revisiones operativas.",
    tourStep5Tip: "Onboarde agentes y simule la sesión de Elena Ramos para comprobar las limitaciones del perfil de ventas."
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string): string => {
    return DICTIONARY[language][key] || DICTIONARY['EN'][key] || String(key);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
}
